package OperacionApp;


/**
* OperacionApp/OperacionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operacion.idl
* miércoles 25 de mayo de 2022 11:22:51 PM CDT
*/

public interface OperacionOperations 
{

  //operaciones (mÃ©todos)
  String ejecutarOperacion (String nombre, int tam);
  int sumar (int num1, int num2);
  int restar (int num1, int num2);
  int multiplicar (int num1, int num2);
  int dividir (int num1, int num2);
  void apagarConexion ();
} // interface OperacionOperations
