package OperacionApp;


/**
* OperacionApp/OperacionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operacion.idl
* miércoles 25 de mayo de 2022 11:22:51 PM CDT
*/

public abstract class OperacionPOA extends org.omg.PortableServer.Servant
 implements OperacionApp.OperacionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ejecutarOperacion", new java.lang.Integer (0));
    _methods.put ("sumar", new java.lang.Integer (1));
    _methods.put ("restar", new java.lang.Integer (2));
    _methods.put ("multiplicar", new java.lang.Integer (3));
    _methods.put ("dividir", new java.lang.Integer (4));
    _methods.put ("apagarConexion", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //operaciones (mÃ©todos)
       case 0:  // OperacionApp/Operacion/ejecutarOperacion
       {
         String nombre = in.read_string ();
         int tam = in.read_long ();
         String $result = null;
         $result = this.ejecutarOperacion (nombre, tam);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // OperacionApp/Operacion/sumar
       {
         int num1 = in.read_long ();
         int num2 = in.read_long ();
         int $result = (int)0;
         $result = this.sumar (num1, num2);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // OperacionApp/Operacion/restar
       {
         int num1 = in.read_long ();
         int num2 = in.read_long ();
         int $result = (int)0;
         $result = this.restar (num1, num2);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // OperacionApp/Operacion/multiplicar
       {
         int num1 = in.read_long ();
         int num2 = in.read_long ();
         int $result = (int)0;
         $result = this.multiplicar (num1, num2);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // OperacionApp/Operacion/dividir
       {
         int num1 = in.read_long ();
         int num2 = in.read_long ();
         int $result = (int)0;
         $result = this.dividir (num1, num2);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // OperacionApp/Operacion/apagarConexion
       {
         this.apagarConexion ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:OperacionApp/Operacion:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Operacion _this() 
  {
    return OperacionHelper.narrow(
    super._this_object());
  }

  public Operacion _this(org.omg.CORBA.ORB orb) 
  {
    return OperacionHelper.narrow(
    super._this_object(orb));
  }


} // class OperacionPOA
