package OperacionApp;


/**
* OperacionApp/Operacion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operacion.idl
* miércoles 25 de mayo de 2022 11:22:51 PM CDT
*/

public interface Operacion extends OperacionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Operacion
